### PR TITLE
Symbiflow vtr

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This is an attempt to get rid of https://github.com/litex-hub/litex-conda-eda/pull/24, which is too big to be merged

### CODE REVIEW

**Comment by PiotrZierhoffer** [comment]
The only sensible way to approach it is to divide, as @mithro suggested. This patchset does vtr, next will be yosys and yosys-plugins. The last step will be to add QL packages

**Comment by PiotrZierhoffer** [comment]
Same files are in sync, using symlinks. I did not use variants as I did not find the proper syntax to alter deps.

I do think these files will desync, as different forks will use different commits

**Comment by PiotrZierhoffer** [comment]
There will also be a separate PR with a commit change for symbiflow-vtr, but I need to discuss the correct one with acomodi et al

**Comment by PiotrZierhoffer** [comment]
Rebased onto current master, with the new stages layout

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by ajelinski** [comment]
All of the functional changes this PR had have already been merged to master through other PRs, including the aforementioned QL packages.

**Pull request closed without merging**
