### PR TITLE
Vtr gui

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This creates a vtr/vtr-gui distinction, similar to the one in Symbiflow, but on `master`.

Please note - I just noticed these packages do rely on symbiflow forks, just on master branch.

Is that expected?

### CODE REVIEW

**Comment by mithro** [comment]
@PiotrZierhoffer -- Needs a rebase before it can be merged.

**Comment by mithro** [comment]
Does this need me to review?

**Comment by PiotrZierhoffer** [comment]
No, I'll merge when I get it green

**Comment by ajelinski** [comment]
`vtr` package has been divided into `vtr` and `vtr-gui` already.

**Pull request closed without merging**
